### ISSUE TITLE
Butterworth filter troubles in Python 2 (works in Python 3)

### ISSUE THREAD

**Issue by smeisler** [pennmem/ptsa_new#56]
When I run the following in Python 2:

b_filter = ButterworthFilter(time_series=base_eegs, freq_range=[58., 62.], filt_type='stop', order=4)
try:
     bw_eegs = b_filter.filter()
except Exception as e:
      print(e)

I get this exception:

__init__() takes at least 3 arguments (2 given)

When running the same code in Python 3, the code executes without error.  Do you know why this may be?

**Comment by mivade** [comment]
Can you provide the full traceback?

@leondavis1 this could be related to the fixes you made recently.

**Comment by smeisler** [comment]
Traceback (most recent call last):

  File "D:/Documents/Kahana/EEG_GUI_C5.py", line 274, in load_eeg
    bw_eegs = b_filter.filter()

  File "C:\Users\smeis\Anaconda3\envs\python2\lib\site-packages\ptsa\data\filters\ButterworthFilter.py", line 62, in filter
    filtered_time_series = TimeSeriesX(filtered_time_series)

TypeError: __init__() takes at least 3 arguments (2 given)

**Comment by mivade** [comment]
Did you upgrade to version 1.1.1? I think this was fixed by @leondavis1.

**Comment by smeisler** [comment]
I just updated it, but the problem still persists, same traceback.

**Comment by smeisler** [comment]
Nevermind, I forgot to update it on my python2 environment as well.  It works fine now.
